#!/usr/bin/env python3
"""Find attractive deterministic presets for the procedural-tree demo."""

import argparse
import json
import random
import subprocess
from pathlib import Path

PROFILES = [
    {"name": "Анна", "label": "Мягкая крона", "branching": 0.62, "curvature": 0.22, "density": 0.94, "vitality": 0.96, "growth": 22},
    {"name": "Марк", "label": "Сильный ствол", "branching": 0.82, "curvature": 0.42, "density": 0.84, "vitality": 0.88, "growth": 28},
    {"name": "Новый", "label": "Без роста", "branching": 0.5, "curvature": 0.2, "density": 0.8, "vitality": 0.9, "growth": 0},
]
ROOT = Path(__file__).resolve().parent.parent

SCORER = r'''
import { TreeGrowthEngine } from './src/plant/generator.ts'
const configs = JSON.parse(await new Response(process.stdin).text())
const score = (config) => {
  const scene = new TreeGrowthEngine(config).setTotalGrowth(config.growth)
  const leaves = scene.crown.regions.flatMap((region) => region.leaves
    .filter((leaf) => leaf.priority <= config.density)
    .map((leaf) => ({ x: region.x + leaf.x, y: region.y + leaf.y })))
  const leftLeaves = leaves.filter((leaf) => leaf.x < 0).length
  const leafBalance = 1 - Math.abs(leftLeaves - (leaves.length - leftLeaves)) / Math.max(1, leaves.length)
  const leftSpan = Math.max(0, -scene.bounds.minX)
  const rightSpan = Math.max(0, scene.bounds.maxX)
  const spanBalance = Math.min(leftSpan, rightSpan) / Math.max(1, leftSpan, rightSpan)
  const width = scene.bounds.maxX - scene.bounds.minX
  const height = scene.bounds.maxY - scene.bounds.minY
  const silhouette = Math.max(0, 1 - Math.abs(width / height - 0.9) / 0.9)
  const richness = Math.min(1, scene.skeleton.branches.length / 420)
  const canopy = Math.min(1, leaves.length / 1_800)
  return { ...config, score: +(35 * spanBalance + 25 * leafBalance + 30 * silhouette + 10 * richness + 10 * canopy).toFixed(2) }
}
process.stdout.write(JSON.stringify(configs.map(score)))
'''


def find_best(candidates: int) -> list[dict]:
    randomizer = random.Random(20260829)
    options = [
        {**profile, "seed": randomizer.randrange(1, 2**32), "progress": 0}
        for profile in PROFILES for _ in range(candidates)
    ]
    result = subprocess.run(
        ["node", "--experimental-strip-types", "--input-type=module", "-e", SCORER],
        input=json.dumps(options), text=True, capture_output=True, check=True, cwd=ROOT,
    )
    scored = json.loads(result.stdout)
    return [max((item for item in scored if item["name"] == profile["name"]), key=lambda item: item["score"]) for profile in PROFILES]


def as_typescript(trees: list[dict]) -> str:
    data = [{key: value for key, value in tree.items() if key != "score"} for tree in trees]
    return f"// Generated by scripts/find_demo_trees.py --write\nexport const demoTrees = {json.dumps(data, ensure_ascii=False, indent=2)} as const\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--candidates", type=int, default=200)
    parser.add_argument("--write", action="store_true", help="write src/demoTrees.ts")
    args = parser.parse_args()
    if args.candidates < 1:
        parser.error("--candidates must be positive")
    trees = find_best(args.candidates)
    if args.write:
        (ROOT / "src/demoTrees.ts").write_text(as_typescript(trees), encoding="utf-8")
    print(json.dumps(trees, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
