// Generated by scripts/find_demo_trees.py --write
export const demoTrees = [
  {
    "name": "Анна",
    "label": "Мягкая крона",
    "branching": 0.62,
    "curvature": 0.22,
    "density": 0.94,
    "vitality": 0.96,
    "growth": 22,
    "seed": 2805649002,
    "progress": 0
  },
  {
    "name": "Марк",
    "label": "Сильный ствол",
    "branching": 0.82,
    "curvature": 0.42,
    "density": 0.84,
    "vitality": 0.88,
    "growth": 28,
    "seed": 2010388843,
    "progress": 0
  },
  {
    "name": "Новый",
    "label": "Без роста",
    "branching": 0.5,
    "curvature": 0.2,
    "density": 0.8,
    "vitality": 0.9,
    "growth": 0,
    "seed": 4059350190,
    "progress": 0
  }
] as const
